[package]
name = "cell-list"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Classic molecular dynamics or n-body data structure"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"

[dev-dependencies]
rand = "0.8.5"
